options:
  general:
    checkVersion: true
    supplySound: true
    verboseLogging: false
  blocks:
    allow: true
    filterMode: blacklist
    useOnlySafeBlocks: true
    fixItemDurability: true
    ignoreEnchantmentBug: false
  entities:
    allow: true
lists:
  blockFilter:
    - DIAMOND_ORE
    - GOLD_ORE
    - LAPIS_ORE
    - IRON_ORE
  allowedEntities:
  # a player
    - PLAYER
  # general entities
    - PAINTING
    - ITEM_FRAME
    - MINECART
    - BOAT
  # mobs
    - CREEPER
    - SKELETON
    - SPIDER
    - GIANT
    - ZOMBIE
    - SLIME
    - GHAST
    - PIG_ZOMBIE
    - ENDERMAN
    - CAVE_SPIDER
    - SILVERFISH
    - BLAZE
    - MAGMA_CUBE
  #  - ENDER_DRAGON
    - WITHER
    - BAT
    - WITCH
  # animals
    - PIG
    - SHEEP
    - COW
    - CHICKEN
    - SQUID
    - WOLF
    - MUSHROOM_COW
    - SNOWMAN
    - OCELOT
    - IRON_GOLEM
    - VILLAGER
  safeBlocks:
    - STONE
    - GRASS
    - DIRT
    - COBBLESTONE
    - WOOD
    - SAPLING
    - SAND
    - GRAVEL
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LOG
    - LEAVES
    - SPONGE
    - GLASS
    - LAPIS_ORE
    - LAPIS_BLOCK
    - DISPENSER
    - SANDSTONE
    - NOTE_BLOCK
    - POWERED_RAIL
    - DETECTOR_RAIL
    - WEB
    - LONG_GRASS
    - DEAD_BUSH
    - WOOL
    - YELLOW_FLOWER
    - RED_ROSE
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - GOLD_BLOCK
    - IRON_BLOCK
    - DOUBLE_STEP
    - STEP
    - BRICK
    - TNT
    - BOOKSHELF
    - MOSSY_COBBLESTONE
    - OBSIDIAN
    - TORCH
    - WOOD_STAIRS
    - CHEST
    - REDSTONE_WIRE
    - DIAMOND_ORE
    - DIAMOND_BLOCK
    - WORKBENCH
    - SOIL
    - FURNACE
    - BURNING_FURNACE
    - SIGN_POST
    - LADDER
    - RAILS
    - COBBLESTONE_STAIRS
    - WALL_SIGN
    - LEVER
    - STONE_PLATE
    - WOOD_PLATE
    - REDSTONE_ORE
    - GLOWING_REDSTONE_ORE
    - REDSTONE_TORCH_OFF
    - REDSTONE_TORCH_ON
    - STONE_BUTTON
    - SNOW
    - SNOW_BLOCK
    - CLAY
    - JUKEBOX
    - FENCE
    - PUMPKIN
    - NETHERRACK
    - SOUL_SAND
    - GLOWSTONE
    - JACK_O_LANTERN
    - DIODE_BLOCK_OFF
    - DIODE_BLOCK_ON
    - TRAP_DOOR
    - SMOOTH_BRICK
    - HUGE_MUSHROOM_1
    - HUGE_MUSHROOM_2
    - IRON_FENCE
    - MELON_BLOCK
    - VINE
    - FENCE_GATE
    - BRICK_STAIRS
    - SMOOTH_STAIRS
    - MYCEL
    - WATER_LILY
    - NETHER_BRICK
    - NETHER_FENCE
    - NETHER_BRICK_STAIRS
    - ENCHANTMENT_TABLE
    - BREWING_STAND
    - CAULDRON
    - ENDER_STONE
    - REDSTONE_LAMP_OFF
    - REDSTONE_LAMP_ON
    - WOOD_DOUBLE_STEP
    - WOOD_STEP
    - SANDSTONE_STAIRS
    - EMERALD_ORE
    - ENDER_CHEST
    - TRIPWIRE_HOOK
    - TRIPWIRE
    - EMERALD_BLOCK
    - SPRUCE_WOOD_STAIRS
    - BIRCH_WOOD_STAIRS
    - JUNGLE_WOOD_STAIRS
    - COMMAND
    - BEACON
    - COBBLE_WALL
    - WOOD_BUTTON