name: DropsToinventory
main: net.amunak.bukkit.plugin_DropsToInventory.DropsToInventory
version: 2
description: This plugin makes some dropped items (configurable) from broken blocks appear in players inventory instead of on ground
#website: http://dev.bukkit.org/server-mods/DropsToInventory/
author: Amunak
load: POSTWORLD